{% set name = "wandb" %}
{% set version = "0.16.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wandb-{{ version }}.tar.gz
  sha256: 8752c67d1347a4c29777e64dc1e1a742a66c5ecde03aebadf2b0d62183fa307c


build:
  number: 0
  noarch: python
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - click >=7.1,!=8.0.0
    - gitpython >=1.0.0,!=3.1.29
    - requests >=2.0.0,<3
    - psutil >=5.0.0
    - sentry-sdk >=1.0.0
    - docker-pycreds >=0.4.0
    - protobuf >=3.19.0,!=4.21.0,<5
    - pyyaml
    - pathtools
    - setproctitle
    - setuptools
    - appdirs >=1.4.3
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
