{% set name = "wandb" %}
{% set version = "0.17.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v{{ version }}.tar.gz
  sha256: 2e5704b131533862d68a2efcde082276948d32e38a8310d9ecb165517ba1bee3


build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cd core && cp ../LICENSE . && go-licenses save . --save_path="./license-files/"  # [unix]
    - cd core && copy ../LICENSE . && go-licenses save . --save_path="./license-files/"  # [win]

  script_env:
    - WANDB_BUILD_SKIP_APPLE=true

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - go-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - setuptools
  run:
    - python
    - appdirs >=1.4.3
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >=3.19.0,!=4.21.0,<5
    - psutil >=5.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=1.0.0
    - setproctitle
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
    - python -c "import wandb; wandb.require('core')"
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - kptkin
    - dmitryduev
    - timoffex
