{% set name = "wandb" %}
{% set version = "0.23.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v{{ version }}.tar.gz
  sha256: 3d06a4880800f54abb06ce96907aa73561e9915d9d9c5c8d7445f3beeb052ea1

build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - go-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - setuptools
    - typing_extensions
  run:
    - packaging
    - pydantic <3
    - six
    - typing >=3.6.4
    - setuptools
    - python
    - appdirs >=1.4.3
    - click >=8.0.1
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >=3.19.0,!=4.21.0,!=5.28.0,<7
    - psutil >=5.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=2.0.0
    - setproctitle
    - typing_extensions >=4.8,<5
    - eval_type_backport

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
    - python -c "import wandb"
  requires:
    - pip

about:
  home: https://github.com/wandb/wandb
  license: MIT
  license_file: LICENSE
  summary: The AI developer platform. Use Weights & Biases to train and fine-tune models, and manage models from experimentation to production.
  doc_url: https://docs.wandb.ai
  dev_url: https://github.com/wandb/wandb

extra:
  recipe-maintainers:
    - jacobromero
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - kptkin
    - dmitryduev
    - timoffex
