{% set name = "wandb" %}
{% set version = "0.17.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/releases/download/v{{ version }}/wandb-{{ version }}.tar.gz
  sha256: bc2307b3f81c6316df79f19af0b7100a4c86d6ff0b147a2c8ab40cab386257e0 


build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - swift 5.9.*  # [osx]
    - go
  host:
    - pip
    - python
    - hatchling
    - typing_extensions
    - swift 5.9.*  # [osx]
  run:
    - python 
    - click >=7.1,!=8.0.0
    - gitpython >=1.0.0,!=3.1.29
    - requests >=2.0.0,<3
    - psutil >=5.0.0
    - sentry-sdk >=1.0.0
    - docker-pycreds >=0.4.0
    - setuptools
    - protobuf >=3.19.0,!=4.21.0,<6
    - pyyaml
    - setproctitle
    - platformdirs
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
    - kptkin
    - dmitryduev
    - timoffex
