{% set name = "wandb" %}
{% set version = "0.12.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wandb-{{ version }}.tar.gz
  sha256: d1c2a6cd3fc57b5a75ff18d4bb69f088d0bd1d0ad22c98005a37e037c85442c7

build:
  number: 0
  noarch: python
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - click >=7.0,<8
    - configparser >=3.8.1
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0
    - pathtools
    - promise >=2.0,<3
    - protobuf >=3.12.0
    - psutil >=5.0.0
    - python >=3.6
    - python-dateutil >=2.6.1
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=1.0.0
    - shortuuid >=0.5.0
    - six >=1.13.0
    - subprocess32 >=3.5.3
    - yaspin >=1.0.0

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - hadim
    - vanpelt
