{% set name = "wandb" %}
{% set version = "0.17.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c2a11c9730c011a547211609eb497dc34d0603a722c3ea4317031f98326b549a


build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli
  script: 
    - {{ PYTHON }} -m pip install . -vv
    - go-licenses save . --save_path="./license-files/"

requirements:
 build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go') }}
    - go-licenses
  host:
    - pip
    - python >=3.7
    - hatchling
  run:
    - python >=3.7
    - click >=7.1,!=8.0.0
    - gitpython >=1.0.0,!=3.1.29
    - requests >=2.0.0,<3
    - psutil >=5.0.0
    - sentry-sdk >=1.0.0
    - docker-pycreds >=0.4.0
    - protobuf >=3.19.0,!=4.21.0,<5
    - pyyaml
    - setproctitle
    - platformdirs
    - setuptools
    - typing_extensions

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: 
    - LICENSE
    - license_files/
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - synapticarbors
    - kptkin
    - dmitryduev
    - timoffex
