{% set name = "wandb" %}
{% set version = "0.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v{{ version }}.tar.gz
  sha256: c6a1e477b778f77d6c81ef8607fbd54fad5d8ce1b447a79b483ca090b9d926fe

build:
  number: 0
  entry_points:
    - wandb=wandb.cli.cli:cli
    - wb=wandb.cli.cli:cli

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - go-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - setuptools
    - typing_extensions
  run:
    - graphql-core >=0.5.0,<2
    - promise >=2.0,<3
    - pydantic >=2.6,<3
    - six >=1.10.0
    - typing >=3.6.4
    - setuptools
    - python
    - appdirs >=1.4.3
    - click >=7.1,!=8.0.0
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >=3.19.0,!=4.21.0,!=5.28.0,<6
    - psutil >=5.0.0
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=2.0.0
    - setproctitle
    - typing_extensions >=4.4,<5
    - eval_type_backport

test:
  imports:
    - wandb
  commands:
    - pip check
    - wandb --help
    - wb --help
    - python -c "import wandb"
  requires:
    - pip

about:
  home: https://github.com/wandb/client
  license: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - kptkin
    - dmitryduev
    - timoffex
