{% set name = "wandb" %}
{% set version = "0.10.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 823b3a59cefc37f0dbb08f4e46216e6e0096d35ced3bd61433e77416735580e8

build:
  number: 0
  noarch: python
  entry_points:
    - wandb=wandb.cli:cli
    - wb=wandb.cli:cli
    - wanbd=wandb.cli:cli
    - wandb-docker-run=wandb.cli:docker_run
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click >=7.0
    - configparser >=3.8.1
    - docker-pycreds >=0.4.0
    - gitpython >=1.0.0
    - gql
    - nvidia-ml
    - psutil >=5.0.0
    - python
    - python-dateutil >=2.6.1
    - pyyaml >=3.10
    - requests
    - sentry-sdk >=0.4.0
    - shortuuid >=0.5.0
    - six >=1.10.0
    - watchdog >=0.8.3
    - setuptools
    - protobuf

test:
  imports:
    - wandb

about:
  home: https://github.com/wandb/client
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A CLI and library for interacting with the Weights and Biases API.
  doc_url: https://docs.wandb.com/
  dev_url: https://github.com/wandb/client

extra:
  recipe-maintainers:
    - rluria14
    - oblute
    - ndmaxar
