schema_version: 1

context:
  name: wandb
  version: 0.26.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/wandb/wandb/archive/v${{ version }}.tar.gz
  sha256: 7357eab838144fe9de9a9e7f385ebf035750189d5521f8ab0d60ae4ede9f3f4e

build:
  number: 0
  python:
    entry_points:
      - wandb=wandb.cli.cli:cli
      - wb=wandb.cli.cli:cli

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ stdlib("c") }}
    - ${{ compiler('c') }}
    - ${{ compiler('go-cgo') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - go-licenses
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - hatchling
    - setuptools
    - typing_extensions
  run:
    - packaging
    - pydantic <3
    - python
    - click >=8.0.1
    - gitpython >=1.0.0,!=3.1.29
    - platformdirs
    - protobuf >4.21.0,!=5.28.0,!=5.29.0,<8
    - pyyaml
    - requests >=2.0.0,<3
    - sentry-sdk >=2.0.0
    - typing_extensions >=4.8,<5
    - six
    - typing >=3.6.4
tests:
  - python:
      imports:
        - wandb
      pip_check: true
  - requirements:
      run:
        - pip
    script:
      - wandb --help
      - wb --help
      - wandb beta leet --help
      - python -c "import wandb"

about:
  license: MIT
  license_file: LICENSE
  summary: The AI developer platform. Use Weights & Biases to train and fine-tune models, and manage models from experimentation to production.
  homepage: https://github.com/wandb/wandb
  repository: https://github.com/wandb/wandb
  documentation: https://docs.wandb.ai

extra:
  recipe-maintainers:
    - jacobromero
    - mxr-conda
    - rluria14
    - oblute
    - ndmaxar
    - vanpelt
    - andrewtruong
    - raubitsj
    - kptkin
    - dmitryduev
    - timoffex
